import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.5.136/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.5.136/pdf.worker.min.mjs';

const $=s=>document.querySelector(s); const dbName='leaf-pdf-library'; const store='books';
let db, books=[], active=null, pdf=null, page=1, zoom=1, busy=false, drag=null;
const el={library:$('#libraryView'),reader:$('#readerView'),grid:$('#bookGrid'),empty:$('#emptyState'),drop:$('#dropzone'),file:$('#fileInput'),book:$('#book'),loader:$('#loader'),title:$('#readerTitle'),meta:$('#readerMeta'),current:$('#pageCurrent'),total:$('#pageTotal'),range:$('#pageRange'),fill:$('#progressFill'),zoom:$('#zoomLabel'),main:$('#readerMain')};

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(store))d.createObjectStore(store,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function tx(mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(b){return new Promise((res,rej)=>{const r=tx('readwrite').put(b);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clearDB(){return new Promise((res,rej)=>{const r=tx('readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function coverFromPdf(p){try{const pg=await p.getPage(1),v=pg.getViewport({scale:.45}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return c.toDataURL('image/jpeg',.72)}catch{return ''}}
async function importPdf(file){if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return toast('Please choose a valid PDF.');try{$('#loader').classList.add('show');const buf=await file.arrayBuffer();const p=await pdfjsLib.getDocument({data:buf.slice(0)}).promise;const cover=await coverFromPdf(p);const b={id:crypto.randomUUID(),name:file.name.replace(/\.pdf$/i,''),blob:new Blob([buf],{type:'application/pdf'}),cover,pages:p.numPages,current:1,added:Date.now(),opened:Date.now()};await put(b);books=await getAll();renderLibrary();toast('Book added to your library.')}catch(e){console.error(e);toast('That PDF could not be opened.')}finally{$('#loader').classList.remove('show')}}
function renderLibrary(){const sort=$('#sortSelect').value;let a=[...books];a.sort((x,y)=>sort==='name'?x.name.localeCompare(y.name):sort==='added'?y.added-x.added:y.opened-x.opened);el.grid.innerHTML=a.map(b=>{const pct=Math.round((b.current/b.pages)*100);return `<article class="book-card"><div class="cover-wrap">${b.cover?`<img src="${b.cover}" alt="">`:`<div class="cover-fallback">${esc(b.name)}</div>`}</div><div class="book-info"><div class="book-name" title="${esc(b.name)}">${esc(b.name)}</div><div class="book-meta">Page ${b.current} / ${b.pages} · ${pct}%</div><div class="card-progress"><i style="width:${pct}%"></i></div><div class="card-actions"><button class="continue" data-open="${b.id}">${b.current>1?'Continue':'Open'} →</button><button data-delete="${b.id}">Delete</button></div></div></article>`}).join('');el.empty.style.display=a.length?'none':'block'}
async function renderPage(n,side='right',target=el.book){const pg=await pdf.getPage(n);const base=pg.getViewport({scale:1});const maxW=innerWidth<760?innerWidth*.86:Math.min(innerWidth*.42,540);const maxH=innerHeight*.78;const s=Math.min(maxW/base.width,maxH/base.height)*zoom;const v=pg.getViewport({scale:s});const c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const sh=document.createElement('div');sh.className='sheet '+side;sh.dataset.page=n;sh.appendChild(c);target.appendChild(sh);return sh}
async function showSpread(){if(!pdf)return;busy=true;el.loader.classList.add('show');el.book.innerHTML='';try{if(innerWidth>=760&&pdf.numPages>1){await Promise.all([renderPage(page%2===0?page-1:page,'left'),page<pdf.numPages?renderPage(page+1,'right'):Promise.resolve()])}else await renderPage(page,'right');updateUI()}finally{el.loader.classList.remove('show');busy=false}}
function updateUI(){el.current.textContent=page;el.total.textContent=pdf.numPages;el.meta.textContent=`${page} / ${pdf.numPages}`;el.range.max=pdf.numPages;el.range.value=page;el.fill.style.width=(page/pdf.numPages*100)+'%';el.zoom.textContent=Math.round(zoom*100)+'%';}
async function turn(dir,fromDrag=false){if(busy)return;const next=page+dir;if(next<1||next>pdf.numPages)return;busy=true;const oldPage=page;page=next;active.current=page;active.opened=Date.now();await put(active);el.meta.textContent=`${page} / ${pdf.numPages}`;const p=await pdf.getPage(next);const base=p.getViewport({scale:1});const maxW=innerWidth<760?innerWidth*.86:Math.min(innerWidth*.42,540);const maxH=innerHeight*.78;const s=Math.min(maxW/base.width,maxH/base.height)*zoom;const v=p.getViewport({scale:s});const c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const t=document.createElement('div');t.className='turn-page '+(dir<0?'leftturn':'');t.style.right=dir>0?'50%':'auto';t.style.left=dir<0?'50%':'auto';c.style.width='100%';c.style.height='100%';c.style.objectFit='contain';t.appendChild(c);el.book.appendChild(t);requestAnimationFrame(()=>{t.style.transform=dir>0?'rotateY(-180deg) skewY(-1deg)':'rotateY(180deg) skewY(1deg)';t.style.clipPath=dir>0?'polygon(0 0,100% 0,88% 100%,0 100%)':'polygon(12% 0,100% 0,100% 100%,0 100%)'});setTimeout(async()=>{await showSpread();busy=false},650)}
async function openBook(id){active=books.find(b=>b.id===id);if(!active)return;try{el.library.classList.add('hidden');el.reader.classList.remove('hidden');el.title.textContent=active.name;const ab=await active.blob.arrayBuffer();pdf=await pdfjsLib.getDocument({data:ab}).promise;page=Math.min(active.current||1,pdf.numPages);active.current=page;active.opened=Date.now();await put(active);await showSpread()}catch(e){console.error(e);toast('Could not open this PDF.');closeReader()}}
function closeReader(){pdf=null;active=null;el.reader.classList.add('hidden');el.library.classList.remove('hidden');books=getAll().then(x=>{books=x;renderLibrary()})}
function fit(){zoom=1;showSpread()} 

$('#uploadBtn').onclick=()=>el.file.click();$('#emptyUpload').onclick=()=>el.file.click();el.file.onchange=e=>e.target.files[0]&&importPdf(e.target.files[0]);el.drop.onclick=()=>el.file.click();['dragenter','dragover'].forEach(x=>el.drop.addEventListener(x,e=>{e.preventDefault();el.drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>el.drop.addEventListener(x,e=>{e.preventDefault();el.drop.classList.remove('drag')}));el.drop.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)importPdf(f)});
$('#sortSelect').onchange=renderLibrary;el.grid.onclick=async e=>{const o=e.target.closest('[data-open]'),d=e.target.closest('[data-delete]');if(o)openBook(o.dataset.open);if(d&&confirm('Delete this book from your browser?')){await del(d.dataset.delete);books=await getAll();renderLibrary()}};$('#clearAll').onclick=async()=>{if(books.length&&confirm('Delete every locally saved book?')){await clearDB();books=[];renderLibrary();toast('Library cleared.')}};
$('#backBtn').onclick=closeReader;$('#nextBtn').onclick=()=>turn(1);$('#prevBtn').onclick=()=>turn(-1);$('#hitRight').onclick=()=>turn(1);$('#hitLeft').onclick=()=>turn(-1);$('#zoomIn').onclick=()=>{zoom=Math.min(2.5,zoom+.1);showSpread()};$('#zoomOut').onclick=()=>{zoom=Math.max(.5,zoom-.1);showSpread()};$('#fitBtn').onclick=fit;$('#pageRange').oninput=e=>{if(!busy){page=+e.target.value;active.current=page;put(active);showSpread()}};$('#fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('leaf-theme',document.body.classList.contains('dark')?'dark':'light')}$('#themeBtn').onclick=toggleTheme;$('#readerTheme').onclick=toggleTheme;if(localStorage.getItem('leaf-theme')==='dark')document.body.classList.add('dark');
window.addEventListener('keydown',e=>{if(el.reader.classList.contains('hidden'))return;if(e.key==='ArrowRight')turn(1);if(e.key==='ArrowLeft')turn(-1);if(e.key==='Escape'&&document.fullscreenElement)document.exitFullscreen?.()});
let sx=0;el.book.addEventListener('pointerdown',e=>{sx=e.clientX;drag=true;el.book.setPointerCapture?.(e.pointerId)});el.book.addEventListener('pointerup',e=>{if(!drag)return;drag=false;const dx=e.clientX-sx;if(Math.abs(dx)>45)turn(dx<0?1:-1)});
window.addEventListener('resize',()=>{if(pdf&&!busy)showSpread()});
await openDB();books=await getAll();renderLibrary();
